[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Humanoid Isaac Frequency Locomotion"
author = "Zheng Pan"
maintainer = "Zheng Pan"
description = "Frequency-based MDP designs for 12-DoF humanoid locomotion"
repository = ""
keywords = ["isaaclab", "humanoid", "locomotion", "frequency"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "humanoid_isaac_freq"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
